### ISSUE TITLE
Problem with 10bit handling

### ISSUE THREAD

**Issue by Selur** [MasterNobody/avs2yuv#2]
I'm using (Avs2YUV 0.24 BugMaster's mod 5):

> LoadPlugin("G:\Hybrid\AVISYN~1\LSMASH~1.DLL")
> LWLibavVideoSource("F:\TestClips&Co\test10bit.mkv",cache=false,stacked=true,format="YUV420P10",repeat=true)
> return last

and 

> avs2yuv  "H:\Output\test.avs" -depth 10 -o - | x264-10bit --crf 18.00 --input-depth 10 --input-csp i420  --fps 25 --input-res 640x352 --output "H:\Output\16_30_22_2310_02.264" -

to reencode a 10bit sample ([test10bit.mkv](https://drive.google.com/drive/folders/0B_WxUS1XGCPASUZibG5XZkRfeTg?usp=sharing)) but the result is all messed up, seems like the 10bit avs input isn't handled properly.

-> is this a bug or am I missing something?

also tried: 

> avs2yuv -raw "H:\Output\test.avs" -depth 10 -o - | x264-10bit --demuxer raw --crf 18.00 --input-depth 10 --input-csp i420  --fps 25 --input-res 640x352 --output "H:\Output\16_30_22_2310_02.264" -

but the output is the same.

different result with 

> LoadPlugin("G:\Hybrid\AVISYN~1\LSMASH~1.DLL")
> LWLibavVideoSource("F:\TestClips&Co\test10bit.mkv",cache=false,stacked=true,format="YUV420P16",repeat=true)
> return last

and 

> avs2yuv  -raw "H:\Output\test.avs" -depth 16 -o - | x264-10bit --demuxer raw --crf 18.00 --input-depth 16 --input-csp i420  --fps 25 --input-res 640x352 --output "H:\Output\16_30_22_2310_02.264" -

but not right

**Comment by MasterNobody** [comment]
1) don't use stacked=true because avs2yuv need memory layout same as real 10-bit format (so stacked=false);
2) either use --demuxer y4m for x264 or use -raw for avs2yuv.
So you script should be:
`LWLibavVideoSource("test10bit.mkv",cache=false,stacked=false,format="YUV420P10",repeat=true)`
and command line:
`avs2yuv -raw -depth 10 test.avs -o - | x264 - --demuxer raw --input-res 640x352 --input-depth 10 --input-csp i420 --fps 25 --crf 18.00 --output test.264`
or
`avs2yuv -depth 10 test.avs -o - | x264 - --demuxer y4m --crf 18.00 --output test.264`

**Comment by Selur** [comment]
Thanks for the info! That helped. :)
